# Controller — discover every service's API key and write them where the controller
# container reads them (/config/keys.env inside it). Pin-by-discovery: nothing is
# committed; keys never leave the host. Idempotent.
# Sourced by provision.sh (lib.sh + .env already loaded). Runs last in ALL.
#
# The controller must be deployed first: its bind-mount dir ($CONFIG/controller) is
# created by Docker as root, and (unlike the linuxserver images) a plain Node image
# doesn't chown /config — so we write keys.env *through* the container with `docker
# cp` (Docker needs no sudo) rather than writing the root-owned host path directly.
docker ps -a --format '{{.Names}}' | grep -qx controller \
  || die "controller container not found — run 'make deploy s=controller' first, then re-provision"

# *arr keys live in each app's config.xml (generated on first start).
rkey=$(arr_apikey "$CONFIG/radarr")
skey=$(arr_apikey "$CONFIG/sonarr")
pkey=$(arr_apikey "$CONFIG/prowlarr")
# Bazarr keeps its key in config.yaml, not config.xml — best-effort (version-only).
bkey=$(grep -oP 'apikey:\s*\K\S+' "$CONFIG/bazarr/config/config.yaml" 2>/dev/null | head -n1 || true)
# Jellyfin: mint (or reuse) a dedicated, revocable key for the controller.
jfkey=$(jellyfin_apikey controller)
[[ -n "$rkey" && -n "$skey" && -n "$jfkey" ]] || die "controller: missing a required key (radarr/sonarr/jellyfin) — deploy + provision those first"

# Build the secrets file in a host-private temp, then copy it into the container.
umask 077
tmp=$(mktemp)
trap 'rm -f "$tmp"' RETURN
cat > "$tmp" <<EOF
# Generated by scripts/provision/controller.sh — DO NOT COMMIT. Re-run to refresh.
RADARR_KEY=$rkey
SONARR_KEY=$skey
PROWLARR_KEY=$pkey
BAZARR_KEY=$bkey
JELLYFIN_KEY=$jfkey
QBIT_USER=$QBIT_USER
QBIT_PASS=$QBIT_PASS
JELLYFIN_ADMIN_USER=$JELLYFIN_ADMIN_USER
JELLYFIN_ADMIN_PASS=$JELLYFIN_ADMIN_PASS
NUC_IP=$NUC_IP
CONTROLLER_PORT=${CONTROLLER_PORT:-8088}
EOF
docker cp "$tmp" controller:/config/keys.env >/dev/null
docker exec controller sh -c 'chmod 600 /config/keys.env' 2>/dev/null || true
ok "controller: keys written (/config/keys.env) — radarr/sonarr/prowlarr${bkey:+/bazarr}/jellyfin + qbit/jellyfin creds"

# Restart so the container re-reads keys.env, then confirm it's serving.
docker restart controller >/dev/null
wait_http "http://localhost:${CONTROLLER_PORT:-8088}/api/status" 30
ok "controller: restarted and serving on :${CONTROLLER_PORT:-8088}"
