#!/usr/bin/env bash
# Shared helpers for the provisioning scripts. Source this — don't execute it.
# All provisioning is idempotent: read current state, only change what differs.

log()  { printf '\033[1;34m▸ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m  ✓ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m  ! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

# wait_http URL [max_seconds] — block until URL answers (any 2xx/3xx/4xx), else die.
# Used to wait for a freshly-started container's web server to come up.
wait_http() {
  local url=$1 max=${2:-180} i=0 code
  while :; do
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "$url" 2>/dev/null || true)
    [[ "$code" =~ ^[2-4][0-9][0-9]$ ]] && return 0
    i=$((i+1)); (( i > max )) && die "timed out after ${max}s waiting for $url (last code: ${code:-none})"
    sleep 1
  done
}

# arr_apikey CONFIG_DIR — print the <ApiKey> from a Radarr/Sonarr/Prowlarr config.xml.
# The key is generated by the app on first start; we read and reuse it (pin-by-discovery).
arr_apikey() {
  local f="$1/config.xml"
  [[ -f "$f" ]] || die "no config.xml at $f — start the container first (make deploy)"
  sed -n 's:.*<ApiKey>\(.*\)</ApiKey>.*:\1:p' "$f" | head -n1
}

# require CMD... — fail early if a required tool is missing.
require() { for c in "$@"; do command -v "$c" >/dev/null || die "missing required tool: $c"; done; }

# jellyfin_apikey APPNAME — get-or-create a Jellyfin API key for APPNAME and print it.
# Uses JELLYFIN_ADMIN_USER/PASS from the environment. Idempotent (reuses an existing key).
jellyfin_apikey() {
  local app="$1" jf="http://${NUC_IP:-localhost}:8096" tok key   # host-net Jellyfin binds to $NUC_IP, not localhost
  tok=$(curl -s -X POST "$jf/Users/AuthenticateByName" \
    -H 'X-Emby-Authorization: MediaBrowser Client="prov", Device="cli", DeviceId="prov", Version="1"' \
    -H 'Content-Type: application/json' \
    -d "$(jq -n --arg u "$JELLYFIN_ADMIN_USER" --arg p "$JELLYFIN_ADMIN_PASS" '{Username:$u,Pw:$p}')" | jq -r '.AccessToken')
  key=$(curl -s "$jf/Auth/Keys" -H "X-Emby-Token: $tok" | jq -r --arg a "$app" '.Items[]?|select(.AppName==$a)|.AccessToken' | head -1)
  if [[ -z "$key" || "$key" == "null" ]]; then
    curl -s -o /dev/null -X POST "$jf/Auth/Keys?app=$app" -H "X-Emby-Token: $tok"
    key=$(curl -s "$jf/Auth/Keys" -H "X-Emby-Token: $tok" | jq -r --arg a "$app" '.Items[]?|select(.AppName==$a)|.AccessToken' | head -1)
  fi
  echo "$key"
}
